package com.example.medvoicetrainer.analysis

import com.example.medvoicetrainer.db.SessionEntity
import org.json.JSONArray
import java.time.LocalDate

/**
 * Ported from app/analysis/demo_tour.py — progress through the keyless-demo guided tour
 * (3 scripted patients). Settings persistence is delegated to the caller via getSetting/
 * setSetting, matching Repository.getSetting/setSetting.
 */

data class TourRecapStats(val sessions: Int, val words: Int, val minutes: Int)

/** id/label/emoji/description/focus for one scripted demo patient, mirrors app/voice/mock_client.py's DEMO_CASES. */
data class DemoCaseInfo(
    val id: String,
    val label: String,
    val emoji: String,
    val description: String,
    val focus: String
)

object DemoTour {
    /**
     * The everyday-English onboarding demo is generated by [SurvivalComposer], so its case id is
     * intentionally not one of the three clinical tour ids below.  It still needs prepared
     * learner turns: otherwise the session UI sees zero sample lines and immediately offers a
     * disabled-looking "finish" button instead of letting a new learner advance the demo.
     */
    private val EVERYDAY_SAMPLE_LEARNER_LINES = listOf(
        "Could you tell me where I can put my suitcase?",
        "Thanks. Is there anything else I should know before we leave?",
        "Great, thank you for your help."
    )

    /** Mirrors app/voice/mock_client.py's DEMO_CASES (id/label/emoji/description/focus only — the
     * scripted patient_lines/user_lines dialogue itself lives in MockVoiceClient, not here). */
    val DEMO_CASES = listOf(
        DemoCaseInfo(
            id = "chest_pain",
            label = "Chest Pain — Mr. Johnson (58M)",
            emoji = "🫀",
            description = "Substernal chest pain × 2 hours. Possible ACS.",
            focus = "OPQRST, ICE, cardiac risk factors"
        ),
        DemoCaseInfo(
            id = "dyspnea",
            label = "Breathlessness — Mrs. Chen (45F)",
            emoji = "🫁",
            description = "Progressive dyspnea × 3 days with productive cough.",
            focus = "Respiratory history, ICE, occupational exposure"
        ),
        DemoCaseInfo(
            id = "abdominal_pain",
            label = "Abdominal Pain — Mr. Patel (35M)",
            emoji = "🩺",
            description = "Acute RLQ pain × 12 hours, migrated from peri-umbilical.",
            focus = "Surgical abdomen, OPQRST, differentials"
        )
    )

    private const val SETTING_COMPLETED = "demo_cases_completed"
    private const val SETTING_DECISION_LAST_SHOWN = "demo_decision_last_shown"
    private const val SETTING_DECISION_LAST_CHOICE = "demo_decision_last_choice"

    /** Ordered scripted-patient ids, mirrors app.voice.mock_client.DEMO_CASES order. */
    val DEMO_CASE_IDS = listOf("chest_pain", "dyspnea", "abdominal_pain")

    /** demo_case_id -> (system, real case id) used to point the encounter tab at a matching case. */
    val DEMO_CASE_PATIENT_FILE = mapOf(
        "chest_pain" to ("cardio" to "cardio_001"),
        "dyspnea" to ("pulm" to "pulm_demo_chen"),
        "abdominal_pain" to ("gi" to "gi_demo_patel")
    )

    /**
     * Prepared learner lines for the keyless sample scenarios.
     *
     * A sample scenario is deliberately not a free-form chat: each tap advances one coherent,
     * prewritten exchange. This keeps the no-key preview honest about being neither live AI nor
     * microphone practice while still showing the shape of a full encounter.
     */
    private val SAMPLE_LEARNER_LINES = mapOf(
        "chest_pain" to listOf(
            "I'm sorry you're experiencing this. Where exactly is the pain, how severe is it, and does it spread anywhere?",
            "What were you doing when the pain started?",
            "Is there any family history of heart disease or heart attacks?",
            "Have you tried anything for the pain, and did it help?",
            "Do you smoke or use any tobacco products?",
            "Do you have any medical conditions, and what medicines do you take?",
            "What worries you most about this, and what were you hoping we could do today?",
            "Because this pain could be serious, we'll check your heart urgently and treat the pain while we investigate."
        ),
        "dyspnea" to listOf(
            "I'm sorry you're feeling so breathless. Is it worse with activity or when you lie flat?",
            "When did this begin, and have you had a cough or brought up any phlegm?",
            "Do you have any chest pain or tightness when you breathe?",
            "Do you take any regular medicines, and do you have any allergies?",
            "Have you ever had a similar breathing problem or been admitted to hospital before?",
            "Do you smoke, or have you had any long-term exposure to dust or chemicals at work?",
            "What are you most concerned might be causing this?",
            "Thank you. We'll check your oxygen level, examine your lungs, and arrange urgent tests to find the cause."
        ),
        "abdominal_pain" to listOf(
            "I'm sorry you're in so much pain. Where did it start, where is it now, and how severe is it?",
            "Is the pain constant, and does anything make it better or worse?",
            "Have you felt sick, vomited, or had a fever?",
            "When did you last open your bowels or pass gas?",
            "Have you ever had pain like this or any abdominal surgery before?",
            "Have you been able to eat or drink since the pain began?",
            "What are you most worried about right now?",
            "Your symptoms need an urgent surgical assessment. We'll control the pain and arrange tests straight away."
        )
    )

    private fun parseIdList(json: String): List<String> {
        return try {
            val arr = JSONArray(json.ifBlank { "[]" })
            (0 until arr.length()).map { arr.getString(it) }
        } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
            emptyList()
        }
    }

    fun getCompletedDemoCases(getSetting: () -> String): List<String> {
        val raw = getSetting()
        if (raw.isBlank()) return emptyList()
        return parseIdList(raw)
    }

    fun markDemoCaseCompleted(caseId: String?, getSetting: () -> String, setSetting: (String) -> Unit) {
        if (caseId.isNullOrEmpty()) return
        val completed = getCompletedDemoCases(getSetting).toMutableList()
        if (caseId in completed) return
        completed.add(caseId)
        setSetting(JSONArray(completed).toString())
    }

    /** Returns (completedCount, total), clamped so a stale extra id can't make progress look >100%. */
    fun tourProgress(completed: List<String>): Pair<Int, Int> {
        val done = completed.count { it in DEMO_CASE_IDS }
        return done to DEMO_CASE_IDS.size
    }

    fun isTourComplete(completed: List<String>): Boolean {
        val (done, total) = tourProgress(completed)
        return total > 0 && done >= total
    }

    /** First scripted patient not yet played, or the last one if all are (re-plays default to the final case). */
    fun getFirstUnseenDemoCaseId(completed: List<String>): String {
        for (id in DEMO_CASE_IDS) {
            if (id !in completed) return id
        }
        return DEMO_CASE_IDS.lastOrNull() ?: "chest_pain"
    }

    /** Reverse lookup of DEMO_CASE_PATIENT_FILE: which demo case id (if any) a real case id belongs to. */
    fun demoCaseIdForRealCaseId(realCaseId: String): String? {
        return DEMO_CASE_PATIENT_FILE.entries.firstOrNull { it.value.second == realCaseId }?.key
    }

    /** The next prepared learner line, or null once the sample conversation is complete. */
    fun nextSampleLearnerLine(realCaseId: String, completedLearnerTurns: Int): String? {
        if (completedLearnerTurns < 0) return null
        val lines = demoCaseIdForRealCaseId(realCaseId)
            ?.let { SAMPLE_LEARNER_LINES[it] }
            ?: EVERYDAY_SAMPLE_LEARNER_LINES
        return lines.getOrNull(completedLearnerTurns)
    }

    fun sampleLearnerLineCount(realCaseId: String): Int {
        return demoCaseIdForRealCaseId(realCaseId)
            ?.let { SAMPLE_LEARNER_LINES[it]?.size }
            ?: EVERYDAY_SAMPLE_LEARNER_LINES.size
    }

    fun markDecisionShown(choice: String?, setSetting: (String, String) -> Unit) {
        setSetting(SETTING_DECISION_LAST_SHOWN, LocalDate.now().toString())
        if (!choice.isNullOrEmpty()) {
            setSetting(SETTING_DECISION_LAST_CHOICE, choice)
        }
    }

    /** Frequency guard: never re-show the post-3rd-case decision twice in a row if the user picked "decide later" today. */
    fun shouldAutoShowDecision(lastShown: String, lastChoice: String): Boolean {
        val today = LocalDate.now().toString()
        return !(lastShown == today && lastChoice == "C")
    }

    /** [shouldAutoShowDecision] over the settings that [markDecisionShown] records. */
    fun shouldAutoShowDecision(getSetting: (String, String) -> String): Boolean =
        shouldAutoShowDecision(
            lastShown = getSetting(SETTING_DECISION_LAST_SHOWN, ""),
            lastChoice = getSetting(SETTING_DECISION_LAST_CHOICE, ""),
        )

    /** Aggregate words spoken/minutes across analyzed keyless-demo sessions for the tour's real-case pairings. */
    fun tourRecapStats(sessions: List<SessionEntity>): TourRecapStats {
        val realCaseIds = DEMO_CASE_PATIENT_FILE.values.map { it.second }.toSet()
        val matching = sessions.filter {
            it.deletedAt == null && it.voiceBackend == "demo" && it.caseId in realCaseIds
        }
        val words = matching.sumOf { it.userWordCount }
        val seconds = matching.sumOf { it.durationSeconds }
        return TourRecapStats(
            sessions = matching.size,
            words = words,
            minutes = Math.round(seconds / 60.0).toInt()
        )
    }
}
